[package]
name = "synth"
version = "0.1.0"
edition = "2021"

[features]
gui = [ "eframe" ]

[dependencies]
rodio = "0.15.0"
midir = "0.8.0"
midly = "0.5.2"
eframe = { version = "0.18.0", optional=true }

